### ISSUE TITLE
使用kuborad-spray安装完成后，traefik ingress转发80端口自动跳转到kuborad页面

### ISSUE THREAD

**Issue by WB-jastme** [eip-work/kuboard-spray#91]
使用kuborad-spray安装完成后，traefik ingress转发80端口自动跳转到kuborad页面
ingress 

```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: reynor
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`eureka-k8s.eastedu.ltd`)
    kind: Rule
    services:
    - name: eureka-headless
      port: 19000
```

traefik 参数定义

```
            - --api.insecure=true
            - --api.dashboard=true
            - --entrypoints.web.Address=:80
            - --entrypoints.https.Address=:443
            - --entrypoints.tcpep.Address=:19000
            - --entrypoints.udpep.Address=:9000
            - --providers.kubernetesingress=true
            - --providers.kubernetescrd=true
```

![image](https://github.com/eip-work/kuboard-spray/assets/5243272/08540852-fe86-491a-89b8-40eb91d2769e)
